// <auto-generated />
using System;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ScanEventService.Data;

#nullable disable

namespace ScanEventService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214190811_ScanEventCreate")]
    partial class ScanEventCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PalletLocationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PalletLocationId");

                    b.ToTable("Pallets");
                });

            modelBuilder.Entity("ScanEventService.Models.PalletLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LocationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PalletLocations");
                });

            modelBuilder.Entity("ScanEventService.Models.ScanEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PalletLocationId")
                        .HasColumnType("uuid");

                    b.Property<JsonElement?>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScannerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PalletId");

                    b.HasIndex("PalletLocationId");

                    b.ToTable("ScanEvents");
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.HasOne("ScanEventService.Models.PalletLocation", "PalletLocation")
                        .WithMany()
                        .HasForeignKey("PalletLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PalletLocation");
                });

            modelBuilder.Entity("ScanEventService.Models.ScanEvent", b =>
                {
                    b.HasOne("Pallet", "Pallet")
                        .WithMany("ScanEvents")
                        .HasForeignKey("PalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ScanEventService.Models.PalletLocation", "PalletLocation")
                        .WithMany()
                        .HasForeignKey("PalletLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pallet");

                    b.Navigation("PalletLocation");
                });

            modelBuilder.Entity("Pallet", b =>
                {
                    b.Navigation("ScanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
